### PR TITLE
introduce new onboarding page

### PR DESCRIPTION
**Pull request by csteinlehner**
Created the first version for a onboarding page as we discussed yesterday. The wording is from the top of my head, so please edit and improve as you can.

### CODE REVIEW

**Comment by csteinlehner** [comment]
@kreativmonkey @haveyaseen Habt ihr mal drauf gekuckt? Kann man das mergen?

**Comment by kreativmonkey** [comment]
i think we can first publish it how it is but we need to improve something later ok?

**Comment by csteinlehner** [comment]
@kreativmonkey yes, for me totally fine, I see it as a first version so we have something. everybody who can improve should please :)

**Comment by csteinlehner** [comment]
@GlOwl Please have look at this PR for the onboarding page and improve.

**Comment by kreativmonkey** [comment]
> @kreativmonkey I think we need the slashes (at least at the buttons). If I'm on the onboarding page and click on the "Join us" Button in the footer, the link points to "onboarding/onboarding"

Thants a bit confusing, i need to check out this!

**Comment by dwt** [comment]
Button works now, the texts are fine for a first draft. I would really like to push this out and then iterate in a new pull request.

**Pull request merged**
